
version: '3.8'

services:
  anime-sync-master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: anime-sync-master
    # Uncomment to provide environment variables if needed
    # environment:
    #   - NODE_ENV=production
